// Generated by CoffeeScript 1.6.1

console.log('nested lib');

exports.data = "I'm nested";

require('../parent-dir.js');

console.log(require("./data.json"));

console.log(require.resolve("resolve"));
