// Generated by CoffeeScript 1.4.0
var data;

exports.say = function() {
  return console.log("lib loaded");
};

data = require('nest/nested-lib.js');

console.log(data);

console.log(require('../readme.md'));
